# Logistic Regression

## Importación de librerias

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importacion de datos

In [2]:
dataset = pd.read_csv('Transform_Hospitalization.csv')


In [3]:
dataset

NUMERO DE DIAS POST BIOPSIA EN QUE SE PRESENTA LA COMPLICACIÓN INFECCIOSA  \
0                                                    1                           
1                                                    1                           
2                                                    1                           
3                                                    2                           
4                                                    2                           
..                                                 ...                           
509                                                  0                           
510                                                  0                           
511                                                  0                           
512                                                  0                           
513                                                  0                           

     BIOPSIA_NEG  FIEBRE_SI  ITU_SI  TIPO DE CULTIVO_HEMOCULTIVO Y UROCULTIVO  \
0              1          1       0                                         0   
1              1          1       0                                         0   
2              1          1       0                                         0   
3              1          0       0                                         0   
4              1          1       1                                         0   
..           ...        ...     ...                                       ...   
509            1          0       0                                         0   
510            0          0       0                                         0   
511            0          0       0                                         0   
512            0          0       0                                         0   
513            1          0       0                                         0   

     TIPO DE CULTIVO_UROCULTIVO  AGENTE AISLADO_E.COLI  \
0                             0                      0   
1                             0                      0   
2                             0                      0   
3                             0                      0   
4                             1                      1   
..                          ...                    ...   
509                           0                      0   
510                           0                      0   
511                           0                      0   
512                           0                      0   
513                           0                      0   

     PATRON DE RESISTENCIA_RESISTENTE A AMPI, CIPRO Y GENTA  \
0                                                    0        
1                                                    0        
2                                                    0        
3                                                    0        
4                                                    1        
..                                                 ...        
509                                                  0        
510                                                  0        
511                                                  0        
512                                                  0        
513                                                  0        

     PATRON DE RESISTENCIA_RESISTENTE A AMPI, SULFA, CEFADROXILO, CEFUROXIMO, CIPRO Y CEFEPIME, CEFOTAXIMA  \
0                                                    0                                                       
1                                                    0                                                       
2                                                    0                                                       
3                                                    0                                                       
4                                          

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 12 columns):
 #   Column                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                 --------------  -----
 0   NUMERO DE DIAS POST BIOPSIA EN QUE SE PRESENTA LA COMPLICACIÓN INFECCIOSA                              514 non-null    int64
 1   BIOPSIA_NEG                                                                                            514 non-null    int64
 2   FIEBRE_SI                                                                                              514 non-null    int64
 3   ITU_SI                                                                                                 514 non-null    int64
 4   TIPO DE CULTIVO_HEMOCULTIVO Y UROCULTIVO                                                               514 non

### Elimino las columnas de 'NO' --FIEBRE_NO, ITU_NO, TIPO DE CULTIVO_NO , AGENTE AISLADO_NO , PATRON DE RESISTENCIA_NO--

In [6]:
# Selecciono las columnas para entrenar 'X' y la columna objetivo 'Y'
# Importante transformar a arrays para no tener qu eescalar a la hora de usar el modelo


X = dataset.iloc[:, :-1].values# menos la ultima columna
y = dataset.iloc[:, -11].values# toma la ultima columna



## División de datos en entrenamiento y prueba

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [8]:
print(X_train[:11])

[[0 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


In [9]:
print(y_train[:11])

[0 1 1 1 0 0 1 1 1 0 0]


## Escalado de funciones

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()# crea el objeto de escalado 
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
print(X_train[:11])

[[-0.14006234 -1.13651514 -0.22146404 -0.07226294 -0.05103104 -0.05103104
  -0.07226294 -0.05103104 -0.05103104  1.21158934 -0.29592334]
 [-0.14006234  0.87988269 -0.22146404 -0.07226294 -0.05103104 -0.05103104
  -0.07226294 -0.05103104 -0.05103104 -0.82536217 -0.29592334]
 [-0.14006234  0.87988269 -0.22146404 -0.07226294 -0.05103104 -0.05103104
  -0.07226294 -0.05103104 -0.05103104 -0.82536217 -0.29592334]
 [-0.14006234  0.87988269 -0.22146404 -0.07226294 -0.05103104 -0.05103104
  -0.07226294 -0.05103104 -0.05103104 -0.82536217 -0.29592334]
 [-0.14006234 -1.13651514 -0.22146404 -0.07226294 -0.05103104 -0.05103104
  -0.07226294 -0.05103104 -0.05103104 -0.82536217 -0.29592334]
 [-0.14006234 -1.13651514 -0.22146404 -0.07226294 -0.05103104 -0.05103104
  -0.07226294 -0.05103104 -0.05103104 -0.82536217 -0.29592334]
 [-0.14006234  0.87988269 -0.22146404 -0.07226294 -0.05103104 -0.05103104
  -0.07226294 -0.05103104 -0.05103104  1.21158934 -0.29592334]
 [-0.14006234  0.87988269 -0.22146404 -0.

<div style="text-align: center; color: yellowgreen; font-size:32px; padding:20px ">
.       ENTRENAMIENTO DEL MODELO      .  <BR>   
   REGRESION LOGISTICA
</div>

In [12]:
# sklearn.linear_model.LogisticRegression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0) # creamos el objeto, y una semilla de randon cero 
model.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [13]:
# Salvamos el modelo entrenado
import joblib as jb

In [14]:
jb.dump(model, 'modelo_entrenado_01.pkl')
#Salvar el objeto de escalado para usarlo en la aplicacion
jb.dump(sc, 'scaler.pkl')

['scaler.pkl']

In [15]:
# Importamos el modelo entrenado
model = jb.load('modelo_entrenado_01.pkl')

## Predecir si se hospitaliza o no.

In [16]:
dataset.columns

Index(['NUMERO DE DIAS POST BIOPSIA EN QUE SE PRESENTA LA COMPLICACIÓN INFECCIOSA',
       'BIOPSIA_NEG', 'FIEBRE_SI', 'ITU_SI',
       'TIPO DE CULTIVO_HEMOCULTIVO Y UROCULTIVO',
       'TIPO DE CULTIVO_UROCULTIVO', 'AGENTE AISLADO_E.COLI',
       'PATRON DE RESISTENCIA_RESISTENTE A AMPI, CIPRO Y GENTA',
       'PATRON DE RESISTENCIA_RESISTENTE A AMPI, SULFA, CEFADROXILO, CEFUROXIMO, CIPRO Y CEFEPIME, CEFOTAXIMA',
       'RANGO PSA_PSA 10+', 'RANGO PSA_PSA 7-7.99', 'HOSPITALIZACION_SI'],
      dtype='object')

In [17]:
#variables a ingresar
ndpb = 0
biopsia_neg = 0  #Biopsia previa
fiebre_si = 0 
itu_si = 0
tc_hyu = 0
tc_u = 0
aa_ecoli = 0
pr_acg =0
pr_asccc = 0
rPSA_entre_7_8 = 0
rPSA_mayor_a_10 = 0



In [18]:
#creo la lista
v_clinicas = [ndpb, 
              biopsia_neg,
              fiebre_si,
              itu_si, 
              tc_hyu,
              tc_u, 
              aa_ecoli,
            pr_acg,
            pr_asccc, 
            rPSA_entre_7_8, 
            rPSA_mayor_a_10
]

In [19]:
# predecir un valor
print(model.predict(sc.transform([v_clinicas]))) # predicion del primer dato de testeo
# print(model.predict(sc.transform([v_clinicas]))) # predicion del primer dato de testeo


[0]


## Predicción de los resultados en el conjunto de prueba

In [20]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


## Matriz de confucion

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score # se importa las 2 librerias
# hacer matriz pero en training
cm = confusion_matrix(y_train, model.predict(X_train))
print(cm)
accuracy_score(y_train, model.predict(X_train))

[[168   0]
 [  0 217]]


1.0

Verdaderos positivos (True Positives, TP): 9 <br>
Verdaderos negativos (True Negatives, TN): 373 <br>
Falsos positivos (False Positives, FP): 2<br>
Falsos negativos (False Negatives, FN): 1<br><br>
Estas métricas se distribuyen de la siguiente manera:<br>

Verdaderos positivos (TP): Estos son los casos en los que el modelo predijo correctamente que la muestra pertenece a la clase positiva (1).<br>
Verdaderos negativos (TN): Estos son los casos en los que el modelo predijo correctamente que la muestra pertenece a la clase negativa (0).<br>
Falsos positivos (FP): Estos son los casos en los que el modelo predijo incorrectamente que la muestra pertenece a la clase positiva (1), cuando en realidad pertenecía a la clase negativa (0).<br>
Falsos negativos (FN): Estos son los casos en los que el modelo predijo incorrectamente que la 

In [22]:
# from sklearn.metrics import f1_score
# print("f1 score for base model is : " , f1_score(y_test,y_pred))   # Puntaje del modelo

print(model.score(X_test,y_test))

1.0
